### ISSUE TITLE
[Bug] Found this during testing for ya.

### ISSUE THREAD

**Issue by MistressPlague** [cassell1337/A.R.E.S#17]
Hangs on this for infinity, cannot use GUI as it doesn't respond due to such: 
![Unity_BExuHYwM0M](https://user-images.githubusercontent.com/36628963/154021720-56c1df61-fb63-45db-94d6-7f83579a5646.png)

**Comment by LargestBoi** [comment]
https://github.com/Dean2k/A.R.E.S ARES has halted development, please use these fork.

**Comment by MistressPlague** [comment]
Will test. I'm simply trying to get bugs fixed.

**Comment by LargestBoi** [comment]
Please report any remaining bugs to the fork and not the official repo ;-;

**Comment by MistressPlague** [comment]
They have issues disabled?

**Comment by LargestBoi** [comment]
Thy again, with the issues I mean, it's their fork, they have just enabled issues
